name: pop_articles
description: NY Times Most Popular Articles

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'


dependencies:
  provider: ^6.0.3
  cached_network_image: ^3.2.1
  shimmer: ^2.0.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.4.1
  flutter_dotenv: ^5.0.2
  flutter_screenutil: ^5.6.0
  timeago: ^3.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  mockito: ^5.4.0
  mocktail: ^0.3.0
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Poppins_Light
      fonts:
        - asset: fonts/Poppins-Light.ttf
    - family: Poppins-Regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: Poppins-Bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf
    - family: Poppins-Medium
      fonts:
        - asset: fonts/Poppins-Medium.ttf
    - family: IBMPlexSansArabic-Regular
      fonts:
        - asset: fonts/IBMPlexSansArabic-Regular.ttf
    - family: IBMPlexSansArabic-Medium
      fonts:
        - asset: fonts/IBMPlexSansArabic-Medium.ttf
    - family: IBMPlexSansArabic-Bold
      fonts:
        - asset: fonts/IBMPlexSansArabic-Bold.ttf
    - family: IBMPlexSansArabic-Light
      fonts:
        - asset: fonts/IBMPlexSansArabic-Light.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
